baseURL = "//sandbox.niceguydave.com"
languageCode = "en-gb"
title = "David Talbot"
theme = "ficunaria"

[deployment]

[[deployment.targets]]
# An arbitrary name for this target.
name = "production"

# Amazon Web Services S3; see https://gocloud.dev/howto/blob/#s3
# For S3-compatible endpoints, see https://gocloud.dev/howto/blob/#s3-compatible
URL = "s3://sandbox.niceguydave.com?region=eu-west-2"
