baseURL = "//sandbox.niceguydave.com"
languageCode = "en-gb"
title = "David Talbot"
theme = "ficunaria"

[deployment]

[[deployment.targets]]
name = "sandbox"
URL = "s3://sandbox.niceguydave.com?region=eu-west-2"
