baseURL = "//sandbox.niceguydave.com"
title = "David Talbot"
theme = "cactus"
languageCode = "en-gb"

enableEmoji = true

[params]

description = "Hey, I'm David :wave: I like cycling, coffee and learning about foreign cultures (sometimes so much that I want to tell the rest of the world about it, which is why this site exists) :wink:"

colortheme = "dark" # dark, light, white, or classic

mainSection = "posts"

mainSectionTitle = "Posts"

[[params.social]]
name = "github"
link = "https://github.com/niceguydave"

[[params.social]]
name = "linkedin"
link = "https://www.linkedin.com/in/detalbot/"

sectionPagesMenu = "main"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[deployment]

[[deployment.targets]]
name = "sandbox"
URL = "s3://sandbox.niceguydave.com?region=eu-west-2"
