name: Deploy Hugo site to AWS

on:
  push:
    branches: ["main"]

permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read    # This is required for actions/checkout

# Define environment variables for simplicity
env:
  AWS_REGION : eu-west-2
  AWS_ROLE_ARN : ${{ AWS_ROLE_ARN }}
  HUGO_VERSION: 0.127.0
  DIST_ID : ${{ CF_DIST_ID }}

# Set bash as the default shell
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1 - Checkout Repo
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      # Step 2 - AWS Authenticate
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: github-action
          aws-region: ${{ env.AWS_REGION }}
      # Step 3 - Install Hugo
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb          
      # Step 4 - Run Hugo
      - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
                    hugo --minify --logLevel info
      - name: Hugo Deploy
        run: |
                    hugo deploy --force --maxDeletes -1 --logLevel info
      - name: Create Invalidation
        run: |
                    aws cloudfront create-invalidation --distribution-id ${{ env.DIST_ID }} --paths "/*"
